name: Cypress Tests + Production Deploy

on:
  schedule:
    - cron: "45 4 16 10 *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start

  # build:
  #   runs-on: ubuntu-latest
  #   needs: cypress-run

  #   steps:
  #     - name: 🚚 Get latest code
  #       uses: actions/checkout@v3

  #     - name: Generate environment variables
  #       run: |
  #         touch .env
  #         echo "PUBLIC_AZURE_MAILCHIMP_FN_URL=${{ secrets.MAILCHIMP_FN_URL }}" >> .env

  #     - name: Install, build, and upload your site output
  #       uses: withastro/action@v1

  #     - name: Deploy to Host MDS 🚀
  #       uses: SamKirkland/FTP-Deploy-Action@4.0.0
  #       with:
  #         server: ${{ secrets.FTP_SERVER }}
  #         username: ${{ secrets.FTP_USERNAME }}
  #         password: ${{ secrets.FTP_PASSWORD }}
  #         local-dir: ./dist/
  #         server-dir: ./
  #         dry-run: false
